version: '3.8'

services:
  web:
    build: .
    command:
      - daphne x_tfoms_project.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command:
      - celery -A x_tfoms_project worker -l INFO
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
