# Generated by Django 5.0.12 on 2025-02-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceerrors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceerrors',
            options={'managed': True},
        ),
    ]
