# Generated by Django 5.0.12 on 2025-03-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_fileupload_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicednrdetails'),
        ),
    ]
