# Generated by Django 5.0.12 on 2025-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_fileupload_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicednrdetails',
            name='invoice_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='Номер счёта'),
        ),
    ]
