# Generated by Django 5.0.12 on 2025-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoicednrdetails_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicednrdetails',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
    ]
